steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/slack-unfurl-kibela', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/slack-unfurl-kibela']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'slack-unfurl-kibela', '--image', 'gcr.io/$PROJECT_ID/slack-unfurl-kibela', '--region', 'asia-northeast1', '--platform', 'managed', '--allow-unauthenticated', '--set-env-vars', 'KIBELA_TEAM=$$KIBELA_TEAM,KIBELA_TOKEN=$$KIBELA_TOKEN,SLACK_TOKEN=$$SLACK_TOKEN']
  secretEnv: ['KIBELA_TEAM', 'KIBELA_TOKEN', 'SLACK_TOKEN']
images:
- gcr.io/$PROJECT_ID/slack-unfurl-kibela
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/KIBELA_TEAM/versions/latest
    env: 'KIBELA_TEAM'
  - versionName: projects/$PROJECT_ID/secrets/KIBELA_TOKEN/versions/latest
    env: 'KIBELA_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/SLACK_TOKEN/versions/latest
    env: 'SLACK_TOKEN'
