steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |-
      gcloud run deploy slack-unfurl-kibela \
      --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE} \
      --region asia-northeast1 \
      --platform managed \
      --allow-unauthenticated \
      --set-env-vars KIBELA_TEAM=$$KIBELA_TEAM,KIBELA_TOKEN=$$KIBELA_TOKEN,SLACK_TOKEN=$$SLACK_TOKEN
  secretEnv: ['KIBELA_TEAM', 'KIBELA_TOKEN', 'SLACK_TOKEN']
images:
- asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/KIBELA_TEAM/versions/latest
    env: 'KIBELA_TEAM'
  - versionName: projects/$PROJECT_ID/secrets/KIBELA_TOKEN/versions/latest
    env: 'KIBELA_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/SLACK_TOKEN/versions/latest
    env: 'SLACK_TOKEN'
