name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: go test
        env:
          KIBELA_TEAM: ${{ secrets.KIBELA_TEAM }}
          KIBELA_TOKEN: ${{ secrets.KIBELA_TOKEN }}
        run: go test
      - name: docker build test
        run: docker build -t bbsakura/etimebot:latest .
